### ISSUE TITLE
Security Errors (dependabot)

### ISSUE THREAD

**Issue by lacymorrow** [snapcrunch/electron-preferences#117]
electron-preferences@2.4.1 requires trim-newlines@^4.0.2 via a transitive dependency on meow@10.1.0

**Comment by lacymorrow** [comment]
electron-preferences@2.4.1 requires glob-parent@^3.1.0 via a transitive dependency on fast-glob@2.2.7

**Comment by pvrobays** [comment]
glob-parent has been updated. trim-newlines 4.0.2 doesn't seem vulnerable. the 4.0.1 is, but we don't use it.
Closing this issue.
