### ISSUE TITLE
Super slick styles!

### ISSUE THREAD

**Issue by lacymorrow** [snapcrunch/electron-preferences#147]
Maybe like slack?

**Comment by pvrobays** [comment]
Am I wrong, or is this (more ore less) a duplicate for #89 ?

**Comment by lacymorrow** [comment]
You could call it a duplicate, I would think of this ticket as "Build a good-looking default theme" and the other as "Build multiple theme presets". I think the point of the ticket gets across in both of them

**Comment by pvrobays** [comment]
I'll leave it open then and rename it to 'Super slick default theme!'.
Any suggestions are welcome. We could let people vote for the best UI proposal😊
