### ISSUE TITLE
preferences.defaults is being overwritten

### ISSUE THREAD

**Issue by lacymorrow** [snapcrunch/electron-preferences#150]
**Describe the bug**
I experienced this bug recently where after using the following function to "reset" all preferences to defaults, setting preference values then began changing the values in `preferences.defaults`

```js
// preferences.defaults = { app: { hidden: null } }

for ( const [ key, value ] of Object.entries( preferences.defaults ) ) {
	preferences.value( key, value )
}

preferences.value('app.hidden', 'hello')
preferences.defaults.app.hidden
// 'hello'
```

**Comment by pvrobays** [comment]
Hi @lacymorrow 
woops.. that's not so ideal :)

It's indeed an issue when you use the `defaults` object and use the objects of its properties to insert them into the preferences. That means in the above example your `preferences.defaults.app` is the same object as `preferences.preferences.app`. Changing either of them will change them in both places. Woopsie...

I'll try to reproduce this and probably fix it by returning a clone of the defaults when accessing them.
