### ISSUE TITLE
Request ability to pass section id to preferences.show()

### ISSUE THREAD

**Issue by macfire** [snapcrunch/electron-preferences#153]
I would like ability to pass a preferences section ID to `preferences.show()`

For example:

```javascript

const preferences = new ElectronPreferences({
  ...
  sections: [
    {
       id: 'about',
        ...
     },
    {
       id: 'settings',
        ...
     },
    {
       id: 'theme',
        ...
     }
  ]
})
```

My menu button opens the preferences window using `preferences.show()`;
and the default section visible is "About", of course, since it is defined first.

I would like to add an additional call 

```javascript
preferences.show("theme")`
```
so that the 'Theme' section is visible first when the preferences window opens.

--

_Note: If this is already possible, please provide syntax.  Thanks._

**Comment by pvrobays** [comment]
Hi @macfire 

Right now this isn't possible, but shouldn't be that hard to implement. We can pass the default when preference window isn't open, or pass an IPC call to a preference window that is already opened.

If you would like to contribute to this repo, please go ahead and open a PR with your suggested solution :)

**Comment by pvrobays** [comment]
Will be part of the 2.8.0 release

**Comment by lvcabral** [comment]
This issue can be closed, as the feature was implemented.
