### ISSUE TITLE
Make debouncing "save preferences" optional

### ISSUE THREAD

**Issue by lacymorrow** [snapcrunch/electron-preferences#154]
I implemented this awhile back, now I'd like the option to turn it off. Pretty simple, I'll have a PR soon.

**Comment by pvrobays** [comment]
How do you suggest to turn it off? `config.debounce = 0`?

**Comment by lacymorrow** [comment]
Yep, exactly. I'll add to the readme

**Comment by lacymorrow** [comment]
Fixed in #155
