### ISSUE TITLE
Conditionally Hide/Show fields based on value of another field

### ISSUE THREAD

**Issue by lacymorrow** [snapcrunch/electron-preferences#160]
I would like the user to choose between a `radio` list of mouse buttons OR an `accelerator`  shortcut as their preferred trigger for an action within my app.

Given a `radio` for "mouse"/"keyboard", I would like to conditionally hide or show the `accelerator` field or the secondary `radio` field, not both.

**Comment by lacymorrow** [comment]
@MKstudio-Tech
> Example: I have a dropdown menu where i want to have values of a list field as options to choose.

**Comment by pvrobays** [comment]
Created an implementation for this with the following functionality:

- add ability to pass JS functions in the preferences object to the renderer
- add ability to programmatically hide fields
- add ability to programmatically hide groups
- add ability to programmatically hide sections

Can be done with a new property on field, group or section items: `hideFunction: (preferences) => { return true; }`
See #177 `preferences.js` file for more info on usage

**Comment by pvrobays** [comment]
Will be in the 2.8.0 release
