### ISSUE TITLE
No 'number' type supported

### ISSUE THREAD

**Issue by Inv1x** [snapcrunch/electron-preferences#168]
**Describe the bug**
I'm trying to add field with type 'number' in section. However, this field didn't appear in the section.

**To Reproduce**
1. Copy following code: `const preferences = new ElectronPreferences({
  browserWindowOpts: {
    resizable: true,
    maximizable: true,
  },
  dataStore: '~/preferences.json',
  sections: [
    {
      id: 'settings',
      label: 'Data',
      icon: 'settings-gear-63',
      form: {
        groups: [
          {
            'label': 'Data',
            'fields': [
              {
                label: 'Market ID',
                key: 'market',
                type: 'number',
              },
              {
                label: 'API Token',
                key: 'token',
                type: 'text',
              },
            ]
          },
        ]
      }
    },
  ],
});`
2. Go to preferences
3. See error

**Expected behavior**
Number field

**Screenshots**
<img width="912" alt="Screenshot 2022-07-17 at 13 10 27" src="https://user-images.githubusercontent.com/78815019/179393560-300ad078-dedd-4a09-9328-4e40bfa00b9d.png">
<img width="528" alt="Screenshot 2022-07-17 at 13 09 32" src="https://user-images.githubusercontent.com/78815019/179393564-fb0c4085-28f3-41b4-9041-986da21bee0a.png">

**Machine (please complete the following information):**
 - OS: macOS 10.14.6
 - Electron version: 19.0.8
 - electron-preferences version: 2.6.0

**Additional context**
As I see, there is no number field in components. Maybe it should be there?

**Comment by pvrobays** [comment]
Hi @Inv1x 
Thanks for posting this bug!

I am able to reproduce this. A quick scan in the code revealed that the we accidently removed the explicit number type in code.
I'll try to merge the fix later today and look for creating a new release.

**Comment by pvrobays** [comment]
Nevermind.. It's released in 2.7.0! :)
