### ISSUE TITLE
Password storage

### ISSUE THREAD

**Issue by petergeneric** [snapcrunch/electron-preferences#176]
**Is your feature request related to a problem? Please describe.**
If user credentials must be configured, it's necessary to use a different settings method to gather them. I suspect given this, plenty of users just end up storing passwords in cleartext on disk when using electron-preferences.

**Describe the solution you'd like**
 - Ideally, electron-preferences would recognise fields of type 'password' and automatically encrypt them using [safeStorage](https://www.electronjs.org/docs/latest/api/safe-storage)
 -  Alternatively, a way to intercept the preferences object before-save and after-load to mutate values - so that users could plug in their own logic using safeStorage, https://github.com/atom/node-keytar, etc.

**Comment by pvrobays** [comment]
Hi @petergeneric. Thanks for your suggestion.

This seems like a good idea. I had no clue about the existence of the safe storage capabilities of electron. Seems like quite a simple implementation.

I would suggest, for backwards compatibility, that we create a new type (e.g. 'password-encrypted') for this functionality.

I'm currently scarce on time, but feel free to contribute and submit your own PR in case this is urgent to you.

**Comment by petergeneric** [comment]
Well, I had a look at building a PR for it myself but it's not as easy as it first seems (at least given my inexperience with Electron & React -- this is my first project to build experience with Electron).

The main problem I ran into is that `safeStorage` is only guaranteed to be available after the `ready` event for non-macOS platforms, so in order to decrypt preference values I think it'd be necessary to make a breaking change (certainly that'd break the example in the repo) to initialise preferences within the `ready` handler.

So I'd rather leave it as an open feature request rather than raising a PR for what might well end up being a large breaking change.

**Comment by pvrobays** [comment]
Hi @petergeneric, sorry for the delayed response.

I understand your concern for creating a breaking change. That's definitely something we should avoid.
To me it seems like our most simple option to go forward is to have the `password` field (or however we'll call it) always be encrypted via the `safeStorage` option. In case the user wants preferences before the `ready` event, these will be available. If he wants to decrypt a `password` preference, he'll has to wait for the `ready` event to decrypt the preference manually via `safeStorage.decryptString(...)`.

Another possibility is to enable the `safeStorage` on the whole preference object. When you opt-in on this, the preferences won't be available until the `ready` event. That way nothing of the preferences window will be readable outside the app. Seems like a good security option to me.

Would either of these options be a solution to your problem? Or are we over engineering things?

**Comment by petergeneric** [comment]
Both approaches would work for me... my 2c is that while there's an elegance to using safeStorage for the whole prefs object, it might be too restrictive for others, so having just passwords always be encrypted seems a better compromise

**Comment by pvrobays** [comment]
@petergeneric Will be part of the 2.8.0 release.
