### ISSUE TITLE
browserWindowOverrides option has no effect on the created preference window

### ISSUE THREAD

**Issue by shiyeling** [snapcrunch/electron-preferences#184]
**Describe the bug**
Trying to change the preference window by setting the browserWindowOverrides option in constructor, but no effect

**To Reproduce**
1. create preference window like this:
`
 const preferences = new ElectronPreferences({
...
browserWindowOverrides: {
    title: 'My title',
  }, 
...
 });
`

**Expected behavior**
the preferenec window should have the specified title.

**Screenshots**
![image](https://user-images.githubusercontent.com/3395635/204760816-b25fd5bc-e0be-4e57-9bfa-4da919476c38.png)

**Machine (please complete the following information):**
 - OS: Windows 10
 - Electron version: 21.1.0
 - electron-preferences version: 2.8.1

**Additional context**
Add any other context we should know

**Comment by pvrobays** [comment]
Hi @shiyeling. Thank you for reporting this bug.

Seems to be an issue due to changes in electron which update the browserWindow title to the HTML header title when loading a page.

I'll create a fix and try to release a patch in the near future.

**Comment by pvrobays** [comment]
Has been released in 2.8.2. Sorry for the delay
